apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-server
  namespace: argocd
spec:
  ignoreDifferences:
  - group: "cilium.io"
    kind: "*"

  project: default
  source:
    repoURL: https://github.com/ben4932042/argo-deploy.git
    targetRevision: main
    path: manifests/jenkins
    helm:
      passCredentials: false
      releaseName: jenkins-server
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 10


